jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: yarn lint:spelling

name: Lint Spelling

on:
  pull_request: ~

  push:
    branches:
      - master
